### ISSUE TITLE
QT 4.8 Download Location Wrong

### ISSUE THREAD

**Issue by oransel** [linux4sam/buildroot-at91#1]
It seems like the QT4.8 download location on 2013.02 branch is wrong. 

The correct path is http://download.qt-project.org/official_releases/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.tar.gz

**Comment by noglitch** [comment]
This buildroot revision is outdated, please use Mainline buildroot: it should perfectly build for SAM9 and SAMA5 products.
