### ISSUE TITLE
PPPD doesn't work well 

### ISSUE THREAD

**Issue by victorK8** [linux4sam/buildroot-at91#11]
Platform: SAMA5D27-WLSOM-EK1

I'm trying to setup a 3g usb modem via pppd.

However, pppd shows the next error
```
Couldn't open the /dev/ppp device: No such device or address
pppd: Please load the ppp_generic kernel module.
```

I check menuconfig and linux-menuconfig options from buildroot and it's all ok!

Any help?

**Comment by ehristev** [comment]
Hi,

Did you select the ppp generic driver as built-in or as a module ?
Have you rebuilt the entire image and checked if the module is loaded ? If you built the ppp_generic as a module, you should see something in the 'lsmod'
also you can check the /lib/modules/<your kernel version>/ directory to see if the module is there.
Other than that, if your module does not autoprobe, you can try to probe it using 'modprobe ppp_generic'

**Comment by victorK8** [comment]
Hi, 

Thanks! I'm trying that.

**Comment by ehristev** [comment]
Hi,

Do you still encounter issues ?

**Comment by victorK8** [comment]
Hi,

Sorry for the delaying, I was on holidays.

I open a ticket on Microchip support. We have no solution about pppd.

Finally, I use qmi-wwan protocol to use the 4G modem. No problem with this protocol.

Thanks !

Víctor
