### ISSUE TITLE
rsylog.service mode flags incorrect

### ISSUE THREAD

**Issue by corby** [linux4sam/buildroot-at91#12]
https://github.com/linux4sam/buildroot-at91/blob/4c594e85d9ddf516e5fe21ce314e31bfc1423578/package/rsyslog/rsyslog.mk#L97

Minor issue, but the system is complaining at startup that the rsyslog.service file at:
`/usr/lib/systemd/system/rsyslog.service`
has executable permissions.

The code sets the mode flags to 755, but they should be 644.

journalctl:
`systemd[1]: Configuration file /usr/lib/systemd/system/rsyslog.service is marked executable. Please remove executable permission bits. Proceeding anyway.`

**Comment by ehristev** [comment]
Hi,

This kind of problem is better to be reported to the buildroot upstream maintainers, for the buildroot project at buildroot.org
We keep a fork of the upstream buildroot here, which is likely older than the last release from upstream project.
Could you please report this there ?

Thanks
