### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Ataraxiall** [linux4sam/buildroot-at91#13]
Good morning,

I am compiling a version for the
sama5d27-wlsom1-ek

the steps I have followed are these.
`sudo apt-get install subversion build-essential bison flex gettext \
libncurses5-dev texinfo autoconf automake libtool mercurial git-core \
gperf gawk expat curl cvs libexpat-dev bzr unzip bc python-dev \
wget cpio rsync xxd`
```
git clone https://github.com/linux4sam/buildroot-external-microchip.git -b 2021.02-at91
git clone https://github.com/linux4sam/buildroot-at91.git -b 2021.02-at91
cd buildroot-at91
 BR2_EXTERNAL=../buildroot-external-microchip/ make sama5d27_wlsom1_ek_headless_defconfig
make
```
and in the end it gives me failure

`/home/user/buildroot-at91/output/build/wilcbtapps-linux4sam-2020.10/transparent_service.c:558:47: warning: passing argument 3 of ‘bt_att_set_debug’ from incompatible pointer type [-Wincompatible-pointer-types]
  558 |   bt_att_set_debug(server->att, att_debug_cb, "att: ", NULL);
      |                                               ^~~~~~~
      |                                               |
      |                                               char *
In file included from /home/user/buildroot-at91/output/build/wilcbtapps-linux4sam-2020.10/transparent_service.c:40:
/home/user/buildroot-at91/output/build/bluez5_utils-5.62/src/shared/att.h:50:24: note: expected ‘bt_att_debug_func_t’ {aka ‘void (*)(const char *, void *)’} but argument is of type ‘char *’
   50 |    bt_att_debug_func_t callback, void *user_data,
      |    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/user/buildroot-at91/output/build/wilcbtapps-linux4sam-2020.10/transparent_service.c:558:3: error: too few arguments to function ‘bt_att_set_debug’
  558 |   bt_att_set_debug(server->att, att_debug_cb, "att: ", NULL);
      |   ^~~~~~~~~~~~~~~~
In file included from /home/user/buildroot-at91/output/build/wilcbtapps-linux4sam-2020.10/transparent_service.c:40:
/home/user/buildroot-at91/output/build/bluez5_utils-5.62/src/shared/att.h:49:6: note: declared here
   49 | bool bt_att_set_debug(struct bt_att *att, uint8_t level,
      |      ^~~~~~~~~~~~~~~~
make: *** [package/pkg-generic.mk:251: /home/user/buildroot-at91/output/build/wilcbtapps-linux4sam-2020.10/.stamp_built] Error 1`
I have tried on two linux machines with ubuntu 20.04 and the same point fails.

some help?

Thanks!

**Comment by ehristev** [comment]
Hi,

A quick way to make it work is to do 
make menuconfig
and then go to External options and deselect the wilc BT apps package.
Then save&exit and do again make.

I will try to see why the building of this package fails. But if you don't need this package at the moment you can remove it from the building and have a working image

**Comment by Ataraxiall** [comment]
Thanks for the response, now it compile .

Thanks!

**Comment by ehristev** [comment]
Buildroot 2021.02.8 has updated bluez5_utils package to 5.62 from 5.55 and this caused a problem with wilcbtapps.
We will update wilcbtapps to work with this newer bluez.
Sorry for the trouble and thank you for reporting this !
