### ISSUE TITLE
Centos 6.4: Buildroot-at91 master branch sama5d3ek_config  failed ....

### ISSUE THREAD

**Issue by mzorr** [linux4sam/buildroot-at91#3]
make sama5d3ek_defconfig
make 
..
..
fails with 

/usr/bin/ld: i386 architecture of input file `printf/.libs/repl-vsnprintf.o' is incompatible with i386:x86-64 output
collect2: ld returned 1 exit status
make[3]: *** [libgmp.la] Error 1
make[3]: Leaving directory `/export/home/bnallapothula/linux4sam/buildroot-at91/output/build/host-gmp-5.0.5'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/export/home/bnallapothula/linux4sam/buildroot-at91/output/build/host-gmp-5.0.5'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/export/home/bnallapothula/linux4sam/buildroot-at91/output/build/host-gmp-5.0.5'
make: *** [/export/home/bnallapothula/linux4sam/buildroot-at91/output/build/host-gmp-5.0.5/.stamp_built] Error 2

System Info :
=======================================================
bash-4.1$ uname -a
Linux 2.6.32-358.23.2.el6.x86_64 #1 SMP Wed Oct 16 18:37:12 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

bash-4.1$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) 

bash-4.1$ g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) 

bash-4.1$ ld -v
GNU ld version 2.20.51.0.2-5.36.el6 20100205
bash-4.1$ 
================================================

Please help resolve.

Tried suggestion from forum - export C/CXXFLAGS & LDFLAGS with " -m32" value, did not help.

**Comment by noglitch** [comment]
This buildroot revision is outdated, please use Mainline buildroot: it should perfectly build for SAM9 and SAMA5 products.
